clearvars;

% generowanie nastaw regulatora dla losowych parametrów œrodowiska
nOfGenParams = 1000;
randomInput = rand(nOfGenParams, 4);
randomOutput = zeros(nOfGenParams, 4);
for i=1:nOfGenParams
    M = randomInput(i,1); % masa wozka
    m = randomInput(i,2); % masa wahadla
    L = randomInput(i,3); % dlugosc od mocowania do srodka ciezkosci wahadla
    b = randomInput(i,4); % wspolczynnik tarcia wozka
    K = strojenie_lqr(M,m,L,b); % nastawy do sterownika liniowo kwadratowego
    randomOutput(i, 1:4) = K;
end


% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 10-Dec-2017 16:56:09
%
% This script assumes these variables are defined:
%
%   randomInput - input data.
%   randomOutput - target data.

x = randomInput';
t = randomOutput';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainscg';  % Scaled conjugate gradient backpropagation.

% Create a Fitting Network
hiddenLayerSize = 4;
net = fitnet(hiddenLayerSize,trainFcn);

% Choose Input and Output Pre/Post-Processing Functions
% For a list of all processing functions type: help nnprocess
net.input.processFcns = {'removeconstantrows','mapminmax'};
net.output.processFcns = {'removeconstantrows','mapminmax'};

% Setup Division of Data for Training, Validation, Testing
% For a list of all data division functions type: help nndivide
net.divideFcn = 'dividerand';  % Divide data randomly
net.divideMode = 'sample';  % Divide up every sample
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Choose a Performance Function
% For a list of all performance functions type: help nnperformance
net.performFcn = 'mse';  % Mean Squared Error

% Choose Plot Functions
% For a list of all plot functions type: help nnplot
net.plotFcns = {'plotperform','plottrainstate','ploterrhist', ...
    'plotregression', 'plotfit'};

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y)

% Recalculate Training, Validation and Test Performance
trainTargets = t .* tr.trainMask{1};
valTargets = t .* tr.valMask{1};
testTargets = t .* tr.testMask{1};
trainPerformance = perform(net,trainTargets,y)
valPerformance = perform(net,valTargets,y)
testPerformance = perform(net,testTargets,y)

% View the Network
view(net)

% Plots
figure, plotperform(tr)
figure, plottrainstate(tr)
figure, ploterrhist(e)
figure, plotregression(t,y)

% Deployment

% Generate MATLAB function for neural network for application
% deployment in MATLAB scripts or with MATLAB Compiler and Builder
% tools, or simply to examine the calculations your trained neural
% network performs.
% genFunction(net,'myNeuralNetworkFunction');
% y = myNeuralNetworkFunction(x);

% Generate a matrix-only MATLAB function for neural network code
% generation with MATLAB Coder tools.
% genFunction(net,'myNeuralNetworkFunction','MatrixOnly','yes');
% y = myNeuralNetworkFunction(x);

% Generate a Simulink diagram for simulation or deployment with.
% Simulink Coder tools.
% gensim(net);
